# Generated by Django 3.2.7 on 2021-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='date_of_meeting',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
