# Generated by Django 3.2.7 on 2021-11-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_habits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habits',
            new_name='ToHabits',
        ),
    ]
